### ISSUE TITLE
Download link shows 404

### ISSUE THREAD

**Issue by dhuma1981** [googlecodelabs/android-topeka#1]
The given link in the fetch Sample project: https://github.com/jkingyens/android-topeka/archive/master.zip is showing 404

**Comment by keyboardsurfer** [comment]
Thank you for reporting this issue. You've come across a legacy link. Please use this one instead
https://github.com/googlecodelabs/android-topeka/archive/master.zip while we fix the codelab.

**Comment by jkingyens** [comment]
Link should now be fixed. Thanks for reporting this!
