### ISSUE TITLE
Gradle Error : Data binding

### ISSUE THREAD

**Issue by alikyo** [googlecodelabs/android-topeka#10]
Hello,

I am getting the following error when starting the Multi-feature part.

`Error:A problem occurred configuring project ':topekaui'.
> Currently, data binding does not work for non-base feature modules.
  Please, move data binding code to the base feature module.
  See https://issuetracker.google.com/63814741 for details`

Should I downgrade my android studio 3 ?

**Comment by RagavendraM** [comment]
Add this in "topeka-base/build.gradle" :
android {
 baseFeature=true}

**Comment by veeSivee** [comment]
I have same issue. when I add `baseFeature=true` in "topeka-base/build.gradle" , I still get the error and I can't sync the project.
When I remove `dataBinding {
        enabled = true
    }` from "topekaui/build.gradle" I can sync the project (success) but I can't Rebuild the project. I got this error :
`Error:(38, 50) error: package com.google.samples.apps.topeka.databinding does not exist`
@RagavendraM can you help me? please.. Thanks so much :)

**Comment by singgihsaputra** [comment]
@veeSivee I don't think this problem have fixed currently, but I will give you an alternative, you can remove data binding inside `topekaui/build.gradle` and `ActivityCategorySelectionBinding` inside `CategorySelectionActivity` and then you can set player manually without data binding

**Comment by keyboardsurfer** [comment]
There is a known bug with [data binding](https://issuetracker.google.com/issues/63814741).
We're working on resolving this issue for the codelab as well.

**Comment by alibitek** [comment]
Yep. The only workaround is to not use data binding in non base feature topekaui module.
See: https://github.com/googlecodelabs/android-topeka/issues/11#issuecomment-338018549

**Comment by jkingyens** [comment]
We now have a feature flag in the latest Android Studio Preview 3.1 to work around this blocking error. Please update to the latest repo and use version 3.1 to go through the sample again. Thanks!

**Comment by etazhar** [comment]
@jkingyens How I can enable data binding in my non-base feature module?
