### ISSUE TITLE
Issue following Codelabs Instant App tutorial

### ISSUE THREAD

**Issue by joan-domingo** [googlecodelabs/android-topeka#13]
Hi,
it happens trying to complete the 5th step of the tutorial:
https://codelabs.developers.google.com/codelabs/android-instant-apps/#4

After following the documentation and before building the APK from the dedicated module I see the next error:
```
Error:Execution failed for task ':apk:preDebugBuild'.
> Android dependency 'com.android.support:support-v4' has different version for the compile (21.0.3) and runtime (26.0.2) classpath. You should manually set the same version via DependencyResolution
```

I'm using AS 3.0 - beta5

I've also tried adding the following lines that I found in an example from Google but it did not work either:
```
api ('com.google.android.instantapps:instantapps:1.0.0') {
        // This is to exclude the transitive dependencies for the support library otherwise
        // the project doesn't compile with the error below.
        //
        // > Android dependency 'com.android.support:support-v4' has different version for the compile (23.3.0) and runtime (25.3.1) classpath. You should manually set the same version via DependencyResolution
        exclude group: 'com.android.support'
    }
```
```
configurations.all {
    resolutionStrategy {
        eachDependency { details ->
            // Force all of the primary support libraries to use the same version.
            if (details.requested.group == 'com.android.support') {
                details.useVersion "26.0.2"
            }
        }
    }
}
```

Any tip?
Thank you

**Comment by RagavendraM** [comment]
You can set in Gradle build:
android{
   compileSdkVersion 26
    buildToolsVersion "26.0.1"

defaultConfig {
    
        minSdkVersion 23
        targetSdkVersion 26

**Comment by joan-domingo** [comment]
Unfortunately it is not solving the issue. I tried changing the minSdk to 23 like you have but still same message. Is it working for you?

**Comment by RagavendraM** [comment]
NO.i'm too struggling with other issue

**Comment by dazza5000** [comment]
Did anyone find a solution to this?

**Comment by eramadani** [comment]
Hi joan-domingo,

after searching several days for a solution. this one worked:

 subprojects {
      project.configurations.all {
         resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.android.support'
                  && !details.requested.name.contains('multidex') ) {
               details.useVersion "26.0.2"
            }
         }
      }
   }

**Comment by joan-domingo** [comment]
Hi eramadani,

I just tried again to follow the tutorial from the beginning with Android Studio 3.0.1 and buildToolsVersion "26.0.2" and it works just fine. I'm not seeing the issue anymore.

Proceeding to close this issue.

PS: If someone still has the same issue, feel free to try the suggestion from @eramadani
