### ISSUE TITLE
non-base features don't need `data-binding`, just remove it~

### ISSUE THREAD

**Issue by SwayChen** [googlecodelabs/android-topeka#18]
https://codelabs.developers.google.com/codelabs/android-instant-apps/#6

![image](https://user-images.githubusercontent.com/6345749/33361225-2af5550a-d512-11e7-95ee-c8b4e6dc139b.png)

```
Error:Currently, data binding does not work for non-base features. Move data binding code to the base feature module.
See https://issuetracker.google.com/63814741.
To enable data binding with non-base features, set the android.enableExperimentalFeatureDatabinding property to true.
```

**Comment by keyboardsurfer** [comment]
Thanks for bringing this up. The codelab has been deprecated. Please use github.com/android/app-bundle-samples instead.
