### ISSUE TITLE
How to make app module as a feature module instead base module? 

### ISSUE THREAD

**Issue by SwayChen** [googlecodelabs/android-topeka#19]
Hi, hope get your responses.

What I want is:
1. create a empty `base module`
2. split app module into some small feature modules

if I create a new `base feature`, and switch app module to feature module, the project shows can't found some resources like strings or mipmap.

Would you deploy show more details about this?

**Comment by keyboardsurfer** [comment]
This is a question that is best suited for [StackOverflow](https://stackoverflow.com/questions/tagged/android-instant-apps) since it does not directly affect the codelab at hand.
