### ISSUE TITLE
wrong pictures in Defining App Links step

### ISSUE THREAD

**Issue by vn7n24fzkq** [googlecodelabs/android-topeka#20]
[https://codelabs.developers.google.com/codelabs/android-instant-apps/#5](url)

activity field should be **.activity.SigninActivity (topeka-base)**
not **.activity.SigninActivity (topekaui)**

Original Image
-------------

![bd0137245932115c](https://user-images.githubusercontent.com/20241522/35780367-4c4fe610-0a15-11e8-819a-a71a70bffaed.png)
![7fa556f0e96093e8](https://user-images.githubusercontent.com/20241522/35780370-51ebc92c-0a15-11e8-900d-2fd2a6365ce5.png)

What it should look like
-------------
![default](https://user-images.githubusercontent.com/20241522/35780474-eef55a02-0a16-11e8-96a3-fceba3c0a71e.PNG)
![123](https://user-images.githubusercontent.com/20241522/35780538-d2aaea28-0a17-11e8-85d2-c7d82b173c41.PNG)

**Comment by keyboardsurfer** [comment]
Thanks for bringing this up. The codelab has been deprecated. Please use github.com/android/app-bundle-samples instead.
