### ISSUE TITLE
"Gradle project refresh failed" when opening project.

### ISSUE THREAD

**Issue by jmnpedrosa** [googlecodelabs/android-topeka#21]
As soon as I import and open the project, and sync starts, I get the error shown below.

In the "Messages" tab:
> **Gradle 'android-topeka' project refresh failed**
> Error:Cause: https://downloads.gradle.org/distributions-snapshots/gradle-4.4-20171031235950+0000-all.zip

In the "Build" tab:
> **android-topeka:** sync failed
> Download https://services.gradle.org/distributions-snapshots/gradle-4.4-20171031235950+0000-all.zip

Attempting to access the URL via Web browser displays a raw XML stating that _"The specified key does not exist."_

**Comment by keyboardsurfer** [comment]
Thanks for reporting this. Fixed within https://github.com/googlecodelabs/android-topeka/commit/7ae3662de7fd87edad0feb8157dc07340b56580a
