### ISSUE TITLE
Error running installed: Default Activity not found

### ISSUE THREAD

**Issue by Shajeel-Afzal** [googlecodelabs/android-topeka#22]
Hi, 

I have created the Muti Feature instant app following the code lab. I want to use Firebase with both instant and installed apps so I have used Google Firebase Tool to Connect Firebase and selected installed module in the window so it applies the Google Play Services Plugin in the "installed" module. 

But as soon as I do that, I am not able to run the project while installed selected from the Project Configuration. It is giving the following error:

`Error running installed: Default Activity not found`

I also tried adding the google play services plugin to the "base" module but still I faced the same error. 

Please help.

**Comment by keyboardsurfer** [comment]
Hi, this issue is out of scope regarding the codelab.
There is an [analytics sample](https://github.com/googlesamples/android-instant-apps/tree/master/analytics) available for instant apps.
