### ISSUE TITLE
ADB install failed for file devman.apk

### ISSUE THREAD

**Issue by EBfVince** [googlecodelabs/android-topeka#23]
Hi,
I have currently a problem to launch **the instant app** on my phone.

**Important informations:**
- I downloaded this repo (no custom changes)
- My Phone : HTC One A9, Android 6.0
- Android Studio 3.2 Canary 18
- Gradle build works
- Installed app works on my phone
- I used to debbug on my phone

There is the log when I try to launch the instant app:

```
06/13 17:40:34: Launching instant
INFO - Analyzing files...

INFO - Checking device...

com.google.android.instantapps.sdk.lib.AdbHelper$AdbCommandException: ADB install failed for file devman.apk
Command output:
[  4%] /data/local/tmp/devman.apk
[  9%] /data/local/tmp/devman.apk
[ 13%] /data/local/tmp/devman.apk
[ 18%] /data/local/tmp/devman.apk
[ 22%] /data/local/tmp/devman.apk
[ 27%] /data/local/tmp/devman.apk
[ 32%] /data/local/tmp/devman.apk
[ 36%] /data/local/tmp/devman.apk
[ 41%] /data/local/tmp/devman.apk
[ 45%] /data/local/tmp/devman.apk
[ 50%] /data/local/tmp/devman.apk
[ 54%] /data/local/tmp/devman.apk
[ 59%] /data/local/tmp/devman.apk
[ 64%] /data/local/tmp/devman.apk
[ 68%] /data/local/tmp/devman.apk
[ 73%] /data/local/tmp/devman.apk
[ 77%] /data/local/tmp/devman.apk
[ 82%] /data/local/tmp/devman.apk
[ 87%] /data/local/tmp/devman.apk
[ 91%] /data/local/tmp/devman.apk
[ 96%] /data/local/tmp/devman.apk
[100%] /data/local/tmp/devman.apk
C:\Users\Adelya\AppData\Local\Android\Sdk\extras\google\instantapps\tools\apks\release\devman.apk: 1 file pushed. 4.0 MB/s (1430720 bytes in 0.339s)
	pkg: /data/local/tmp/devman.apk

Success


Error while Uploading and launching Instant App
```

What went wrong ? Do you have any idea ?

**Comment by UlissesGomes** [comment]
Hey. I was having the same problem.

I solved this

1 - Go to "C:\Users\your.user\AppData\Local\Android\Sdk\extras\google" and delete the directory "instantapp"

2 - Ok, now update your Android Studio and Android SDK Intant App (maybe this will update itself), but check SDK Manager > SDK Tools and check Google Play Instant Development SDK

3 - Go to phone or emulator and acess Settings > Google > InstantApp, clean all instants apps installed

4 - Reboot our phone

5 - Go to Task Manager look for "adb.exe" and finish task

**Comment by bishtajay** [comment]
Hey I have same problem but in place of devman is supervisor_x86.
I was updated my instantapps sdk and also update android studio.please help.
Thanks in advance

**Comment by keyboardsurfer** [comment]
Thanks for bringing this up. The codelab has been deprecated. Please use github.com/android/app-bundle-samples instead.
