### ISSUE TITLE
Documentation on codelab

### ISSUE THREAD

**Issue by ff55lab** [googlecodelabs/android-topeka#25]
https://codelabs.developers.google.com/codelabs/android-instant-apps/#5

At the point 6, the given host url for categories and quiz are invalid.

http://topeka.samples.androidinstantapps.com/categories to CategorySelectionActivity
http://topeka.samples.androidinstantapps.com/quiz to QuizActivity

Have to exclude the ".samples" keyword from both host url.

http://topeka.androidinstantapps.com/categories to CategorySelectionActivity
http://topeka.androidinstantapps.com/quiz to QuizActivity

Thanks.

**Comment by keyboardsurfer** [comment]
Thanks for bringing this up. The codelab has been deprecated.
