### ISSUE TITLE
error: uses-sdk:minSdkVersion 14 cannot be smaller than version 21 declared in library 

### ISSUE THREAD

**Issue by fcmeca** [googlecodelabs/android-topeka#28]
When I add the category module to the project and the gradlew files, an error occurs when trying to run the app.
This is the error:

Manifest merger failed : uses-sdk:minSdkVersion 14 cannot be smaller than version 21 declared in library [:categories] /Users/admin/Development/Projects/AndroidStudio/android-topeka-singleModule/categories/build/intermediates/manifests/full/debug/AndroidManifest.xml as the library might be using APIs not available in 14
	Suggestion: use a compatible library with a minSdk of at most 14,
		or increase this project's minSdk version to at least 21,
		or use tools:overrideLibrary="com.google.samples.apps.topeka.categories" to force usage (may lead to runtime failures)

**Comment by keyboardsurfer** [comment]
Thanks for bringing this up. The codelab has been deprecated. Please use github.com/android/app-bundle-samples instead.
