### ISSUE TITLE
Error while Uploading and registering Instant App

### ISSUE THREAD

**Issue by ancymathai** [googlecodelabs/android-topeka#3]
device: samsung galaxy j7
api: 23 
Side loading instant app failed: Failure when trying to read bundle. Unable to connect to Google Play Service. ConnectionResult{statusCode=API_UNAVAILABLE, resolution=null, message=null}

**Comment by jkingyens** [comment]
Either the version of Google Play Services or the device itself is not supported by Android Instant Apps at this time.  Could you try the emulator instead?
