### ISSUE TITLE
External Storage not supporting in instant app

### ISSUE THREAD

**Issue by 8463055730** [googlecodelabs/android-topeka#30]
I am facing problem in android instant apps
as I am having multiple permissions in app:- 
 Manifest.permission.ACCESS_FINE_LOCATION, 
Manifest.permission.READ_EXTERNAL_STORAGE, 
Manifest.permission.READ_PHONE_STATE,
 Manifest.permission.READ_SMS

**but I am only getting Location permission in instant app,not getting another permissions**
so what I do
Please help me as soon as possible.

**Comment by keyboardsurfer** [comment]
Thanks for bringing this up. The codelab has been deprecated. Please use github.com/android/app-bundle-samples instead.
