### ISSUE TITLE
Unable to build the project 

### ISSUE THREAD

**Issue by shashankSkydale** [googlecodelabs/android-topeka#34]
unable to build the project getting below error, please assist:

`ERROR: Could not download kotlin-reflect.jar (org.jetbrains.kotlin:kotlin-reflect:1.1.4-3): No cached version available for offline mode`

**Comment by keyboardsurfer** [comment]
Thanks for bringing this up. The codelab has been deprecated. Please use github.com/android/app-bundle-samples instead.
