### ISSUE TITLE
Please update instant app codelabs to Kotlin 1.3.10 or higher.

### ISSUE THREAD

**Issue by RoarGronmo** [googlecodelabs/android-topeka#35]
Instant app codelabs is lacking behind due to updates in both Kotlin and Android Studio. Please update it from Kotlin 1.2.10 to 1.3.40 and do the necessary codechanges to comply, Android 3.5 is soon released...

**Comment by keyboardsurfer** [comment]
Thanks for bringing this up. The codelab has been deprecated. Please use github.com/android/app-bundle-samples instead.
