### ISSUE TITLE
Error at openning the project

### ISSUE THREAD

**Issue by elye** [googlecodelabs/android-topeka#36]
On opening the project (The complete branch) using Android Studio 3.4, it straight away error out with the below message
```
ERROR: Cause: https://downloads.gradle-dn.com/distributions-snapshots/gradle-4.0-20170417000025+0000-all.zip
```

Did I miss anything?

**Comment by keyboardsurfer** [comment]
Thanks for bringing this up. The codelab has been deprecated. Please use github.com/android/app-bundle-samples instead.
