### ISSUE TITLE
The instant-app guide is outdated

### ISSUE THREAD

**Issue by tdekoning** [googlecodelabs/android-topeka#38]
The guide is still using deprecated `com.android.feature` gradle module types, while `com.android.dynamic-feature` is the way to go.

Both:
https://codelabs.developers.google.com/codelabs/android-instant-apps and https://codelabs.developers.google.com/codelabs/android-multi-feature-instant-app are outdated.

**Comment by keyboardsurfer** [comment]
Thanks for bringing this up. The codelab has been deprecated.
