### ISSUE TITLE
Error while Running a Multi-Feature topeka Instant App

### ISSUE THREAD

**Issue by ancymathai** [googlecodelabs/android-topeka#6]
Error:A problem was found with the configuration of task ':topekaapk:dataBindingExportBuildInfoDebug'.
> Directory 'F:\downloads\topeka\topekaapk\build\intermediates\data-binding-info\debug' specified for property 'xmlOutFolder' does not exist.

**Comment by jkingyens** [comment]
I am unable to reproduce this issue. Did you try cleaning your build first? If you are still seeing this issue try repeating the codelab from scratch.
