### ISSUE TITLE
 Package name of your Instant App APKs should be the same as your app's package name.

### ISSUE THREAD

**Issue by younas-bangash** [googlecodelabs/android-topeka#7]
I follow exactly same procedure to my app but when I generate the sign apk it show me error  " Package name of your Instant App APKs should be the same as your app's package name." and I can not rename the app module because then it will conflict the base app module and I try it

**Comment by jkingyens** [comment]
Is the name of both your instant app and app package name "com.foobar"?

**Comment by protoss5482** [comment]
I have same problem. How fix it?

**Comment by keyboardsurfer** [comment]
You can rename the base module to use a different namespace than your instant or installable app.

**Comment by protoss5482** [comment]
I have:

**Installed:** 
manifest: com.company_name.app_name.app  
gradle: applicationId "com.company_name.app_name"

**Base:** 
manifest: com.company_name.app_name with google-services.json
gradle: applicationId none

**Feature:** 
manifest: com.company_name.app_name.feature
gradle: applicationId none

**Instant**
manifest: none
gradle: applicationId "com.company_name.app_name.app"

What's wrong?

**Comment by keyboardsurfer** [comment]
This is not an issue on the codelab, but a general development question. Please refer to [StackOverflow](https://stackoverflow.com/questions/tagged/android-instant-apps).

Feel free to link your question here as well.
